### ISSUE TITLE
Include bug workaround for top level gdocs

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/readthedocs#10]
Problem
--------

We tried using the include directive to include a toctree file populated with links to Google Drive documents at the top level of the `/readthedocs` folder in Google Drive. We were hoping to just build this without touching the `index.rst` file. It would suck in the links generated for the first toctree element:

```
Subutai Documentation
=====================

Join the Subutai Horde! Be part of the P2P Cloud Crowd.

.. _1:

.. toctree::
   :maxdepth: 2
   :caption: General

.. include <path/to/generated/toctreefile>
``` 

This did **NOT** work. Whether we do not know how to use the sphinx include directive or it has a bug. After some time we decided on a wacky workaround that we know will work.

Workaround
------------

So we cannot use this include directive to automatically inject the links for top level files from gdocs. To do this we use a workaround. We chopped up the `index.rst` file into two files:

- [index_a](https://github.com/subutai-io/readthedocs/blob/master/index_a)
- [index_b](https://github.com/subutai-io/readthedocs/blob/master/index_b)

We will generate the index.rst by:

1. Copying the index_a file to index.rst
2. Appending all the top level links for the _1 toctree entry into the index.rst
3. Appending index_b to index.rst

Pay attention to the need for spaces and newlines. This is python land where sphinx is sensitive to it.

**Comment by nurik23** [comment]
Can you please explain step number 2: Appending all the top level links for the _1 toctree entry into the index.rst.
Which links are top level?
What is the _1 toctree?
Where is the _1 toctree?

**Comment by akarasulu** [comment]
I finished this myself.
