### ISSUE TITLE
Disqus Comment system for docs

### ISSUE THREAD

**Issue by efeefe** [subutai-io/readthedocs#8]
Is it possible to add a Disqus box by the end of every page of documentation? It seems to be a good way to catch inconsistencies or insufficient information here. There's an extension to Sphinx:

https://robpol86.github.io/sphinxcontrib-disqus/v1.1.0/index.html

**Comment by akarasulu** [comment]
We can do anything we like. I can have these added easily. Just give me the text to add.

**Comment by efeefe** [comment]
Here's the universal code to embed a Disqus box on the bottom of every doc page:

https://subutai-io.disqus.com/admin/settings/universalcode/

**Comment by akarasulu** [comment]
@josealbertorodriguesjunior @efeefe was this done?

**Comment by josealbertorodriguesjunior** [comment]
@efeefe I have permission to access this ( https://subutai-io.disqus.com/admin/settings/universalcode/ )?

**Comment by efeefe** [comment]
just sent you by email, copying also @akarasulu and @jeehmilena

**Comment by akarasulu** [comment]
This is already done.
