### ISSUE TITLE
Sorting Hub documentation

### ISSUE THREAD

**Issue by efeefe** [subutai-io/readthedocs#9]
In trying to organize docs about the Hub, I have sketched a rough sitemap. Still undecided on which parts of it should be featured first - whether the left menu or the right one:

https://embed.kumu.io/f87b9f156e99a9c13f225d4e8250c818

Also, some doc items are sort of orphans, as can be seen in the sitemap: E2E Plugin (does it belong to the Hub's documentation at all?), EZ Desktop (perhaps right after "Environments", even though EZ Desktop is not featured in the left sidebar menu), and Blueprint/User variables (maybe after the Bazaar?). Any opinions?

**Comment by amol4anoff** [comment]
@efeefe E2E plugin is on Hub side as it's required to create environment (Hub side). EZ desktop - can be somewhere near p2p, it makes remote access to container's desktop. Blueprint/User variables after Bazaar - good, agree.

**Comment by efeefe** [comment]
Cool. New map here: https://embed.kumu.io/eb76f9f0a800a8eee4c8329b4f293335

**Comment by amol4anoff** [comment]
@efeefe looks great.
